### ISSUE TITLE
Sheet not showing, Mail opening instead. 

### ISSUE THREAD

**Issue by ruxiang05** [flexible-agency/react-native-email-link#101]
I have Mail and Gmail installed. However, the app is not showing the sheet, but opens the Mail app instead.

This is my config in `app.json`
```
"plugins": ["react-native-email-link"],
"infoPlist": {
        "LSApplicationQueriesSchemes": [
          "message",
          "readdle-spark",
          "airmail",
          "ms-outlook",
          "googlegmail",
          "inbox-gmail",
          "ymail",
          "superhuman",
          "yandexmail"
        ]
      }
 ```
 Using latest version `1.31.1`. I am using `Expo`
 Testing on iOS physical device.
 What is happening here? Am I missing something?

**Comment by tschoffelen** [comment]
Did you rebuild the native app after making those changes to your app.json file?

**Comment by ruxiang05** [comment]
Yes, i rebuilt it

**Comment by i8ramin** [comment]
I am experiencing the same thing. Always opens up the Mail app even though I have Gmail app installed.

**Comment by sammiepls** [comment]
I am experiencing the same thing as well, only the Mail app will open. I even tried uninstalling the Mail app, where a dialog would then prompt me to install the Mail app from the App Store. This works fine on Android, just only on iOS it opens the mail app even if user has set the default app to something else like Gmail.
