### ISSUE TITLE
Always open Outlook on Inbox screen? 

### ISSUE THREAD

**Issue by jameschetwood** [flexible-agency/react-native-email-link#102]
When I open Outlook for the first time it opens the default screen which is the inbox. However if Outlook is already open in the background and on a different screen (eg reading an email), then it's opened on this screen. Is there a way to instead always open Outlook on the start / inbox scren?

**Comment by tschoffelen** [comment]
As far as I know there unfortunately isn't a specific URL scheme to open Outlook on a specific screen...
