### ISSUE TITLE
Can't catch error if no Email client on Android

### ISSUE THREAD

**Issue by pastoreli** [flexible-agency/react-native-email-link#104]
I'm trying to handle with no email app exception, but it's not work on **Android**, because its never fall the `.catch` and `.then` always return null as result

_Alert: Its work fine in IOS_

```
openInbox({
 title: 'Title',
 message: 'Message',
}).catch((err: EmailException) => {
 if (err.message === 'No email apps available') {
  alert('No email');
  } else {
   alert('Default error');
  }
 });
```

**Comment by tschoffelen** [comment]
I think this information is indeed currently not passed back from the native bit of the Android integration to the javascript side. Definitely something we could add I think.

**Comment by andrew-blackwood** [comment]
> I think this information is indeed currently not passed back from the native bit of the Android integration to the javascript side. Definitely something we could add I think.

This would be much appreciated. The lack of throwing an error when no email client is found on Android is potentially a blocker for me right now in using this library.

**Comment by tschoffelen** [comment]
Anyone able to do a PR for this?

**Comment by andrew-blackwood** [comment]
> Anyone able to do a PR for this?

Yes, I can. I have already created the fix in a forked repo - will create the PR later today.
