### ISSUE TITLE
Android: incorrectly using facebook package names

### ISSUE THREAD

**Issue by udeyrishi** [flexible-agency/react-native-email-link#35]
I noticed that the android source files are declared under the `com.facebook.*` package names. For instance: https://github.com/tschoffelen/react-native-email-link/blob/master/android/src/main/java/com/facebook/react/modules/email/EmailModule.java#L1.

Since this is not a first-party facebook lib, we should consider renaming it. This will be a non-backwards compatible breaking change though.

**Comment by tschoffelen** [comment]
Agreed! Let’s work towards a 2.0 version once we have the open PRs merged!

**Comment by tschoffelen** [comment]
Other changes have been merged, so feel free to create a PR to rename the packages if you feel like it!

Otherwise I'll do it at some point, but don't think I'll get time to do it properly until next month.

**Comment by switch13** [comment]
Just wanted to mention to anyone upgrading from a previous version and getting the following error: error: package com.facebook.react.modules.email does not exist import com.facebook.react.modules.email.EmailPackage;

I just needed to go into android/app/src/main/java/YOURAPP/MainApplication.java and change

this: import com.facebook.react.modules.emails.EmailPackage;
to this: import agency.flexible.react.modules.email.EmailPackage;

@tschoffelen not sure if there's a ticket to fix for upgrades, or how to suggest one but it might be helpful

**Comment by tschoffelen** [comment]
You shouldn't need to manually include this in your MainApplication.java anymore if you're on a recent version of React Native, since it now has auto-imports.
