### ISSUE TITLE
Url encode body breaks on Android Gmail

### ISSUE THREAD

**Issue by emielvanliere** [flexible-agency/react-native-email-link#76]
Hi,

Thanks for creating this lib :-)

Your recent change in https://github.com/tschoffelen/react-native-email-link/pull/71 breaks the email body on Android for me. Gmail now renders the email encoded e.g. `Hi%20there%20` etc.

Reverting the 'fix' in said PR resolves the issue for me.

This happens with Gmail 2020.06.14 (=latest version) on Android 9. I haven't tried other clients.

Perhaps `openComposer` needs an option `encodeBody` that controls this behaviour?

**Comment by radko93** [comment]
It also breaks some other emails on iOS. I think everyone has to do it by himself.

**Comment by cesar3030** [comment]
Hey @radko93 @emielvanliere,
I also had this issue so I added the `encodeBody` body flag you requested. 

Cheers!
