### ISSUE TITLE
iOS: Question / Open action sheet in ios

### ISSUE THREAD

**Issue by enzzoperez** [flexible-agency/react-native-email-link#80]
Hello ✋ , I would like to know if is possible to get this behaviour in ios

![imageslack](https://user-images.githubusercontent.com/22937791/112495263-80ac0280-8d62-11eb-82d8-c265cdc702eb.png)

As you see there, when I click a button,an action sheet open and you can to select what email client open.

In this moment, when I want to open some client email I get this screen 

<img width="493" alt="Screen Shot 2021-03-25 at 12 08 05" src="https://user-images.githubusercontent.com/22937791/112495646-d84a6e00-8d62-11eb-8da7-1df01bca1093.png">

so, how can I get a behaviur like firs screen?, It is possible?.. Can I pass to the `openInbox()` function some params to open the email client that I want?

Thank u!

**Comment by tschoffelen** [comment]
Hi! The library will automatically show the available options in a menu like the screenshots you've attached when there's more than 1 option available. If there's only one option, it will immediately open that app.

If you have multiple apps installed but the menu is not shown, it probably means you skipped the step in the README to [whitelist the apps](https://github.com/flexible-agency/react-native-email-link#2-update-your-infoplist) in your `Info.plist` file.

**Comment by enzzoperez** [comment]
Thank for response @tschoffelen , yes I already have set the `Info.plist` and the package work btw, but as the second screen.. I dont know if this is beacause of ios version, but the behaviour that I search is like as the first screen (an action sheet like slack)

I mean, the only thing that I lack is the "UI" for the modal, so I thought make an action sheet, and the in each item call to `openInbox` function and open touched email client

**Comment by tschoffelen** [comment]
`openInbox` already has that sheet built in, see: https://github.com/flexible-agency/react-native-email-link/blob/master/src/ios.js#L181

**Comment by enzzoperez** [comment]
Ooh, that's right!, thank you @tschoffelen , I will review again the app
